name: On-demand dataset release
on:
  # Only allow manual triggers for now
  workflow_dispatch:
    manual: true

jobs:
  provision_droplet:
    name: Trigger Steve
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      IPAddress: ${{ steps.ipAddress.outputs.ipAddress }}
    steps:
      - uses: actions/checkout@v2

      - name: SSH into droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STEVE_IP_ADDRESS }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 360m
          script: |
            rm -rf ~/DASEA
            source ~/.profile
            git clone git@github.com:dependulum/DASEA.git
            cd DASEA
            poetry env use /usr/bin/python3.9
            poetry install
            export ZENODO_API_TOKEN=${{ secrets.ZENODO_API_TOKEN }}
            nohup bash bin/release/trigger_dataset_generation.sh &
