name: On-demand dataset release
on:
  # Only allow manual triggers for now
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo 1234
        id: hello
      
      - name: Get IP of droplet
        run: echo ${{ steps.hello.outputs.value }}
        
      #- name: SSH into droplet
      #  uses: appleboy/ssh-action@master
      #  with:
      #    host: ${{ secrets.HOST }}
       #   username: ${{ secrets.USERNAME }}
        #  key: ${{ secrets.SSH_PRIVATE_KEY }}
         # script: whoami
        
#      - name: Destroy droplet
#        run: doctl compute droplet delete DASEA-tool
