name: On-demand dataset release
on:
  # Only allow manual triggers for now
  workflow_dispatch:
  # Only trigger, when the build workflow succeeded
  # TODO: uncomemnt me
  # workflow_run:
  #   workflows: ['Build And Test Workflow']
  #   types:
  #     - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  provision_droplet:
    # FIXME:
    if: ${{ false }} # disable for now
    name: Provision droplet
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      IPAddress: ${{ steps.ipAddress.outputs.ipAddress }}
    steps:
      - uses: actions/checkout@v2

      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.1.0
        with:
          token: ${{secrets.DO_ACCESS_TOKEN}}
      - name: Provision droplet
        run: >
          doctl compute droplet create
          --image ubuntu-20-04-x64
          --size s-1vcpu-1gb
          --region ams3
          --wait
          --ssh-keys ${{secrets.SSH_PUBLIC_KEY_FINGERPRINT}},${{secrets.DO_SSHKEY_JHI}},${{secrets.DO_SSHKEY_KOLS}},${{secrets.DO_SSHKEY_PEBU}}
          DASEA-tool

      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - name: Get IP of droplet
        run: |
          echo "::set-output name=value::$(doctl compute droplet get --format "PublicIPv4" --no-header DASEA-tool)"
        id: SSH_HOST

      - name: Echo IP
        run: |
          echo "IP: ${{ steps.SSH_HOST.outputs.value }}"

      - name: SSH into droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.SSH_HOST.outputs.value }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: whoami

      - id: IPAddress
        run: echo "::set-output name=ipAddress::${{ steps.SSH_HOST.outputs.value }}"

  release_dataset:
    name: Release dataset
    runs-on: ubuntu-latest
    # needs: provision_droplet
    steps:
      - uses: actions/checkout@v2

      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.1.0
        with:
          token: ${{secrets.DO_ACCESS_TOKEN}}

      # - run: echo ${{ needs.provision_droplet.outputs.IPAddress}}

      - name: SSH into droplet
        uses: appleboy/ssh-action@master
        with:
          # host: ${{ needs.provision_droplet.outputs.IPAddress}}
          host: 165.22.199.251
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: whoami

      - name: Copy DaSEA tool
        uses: appleboy/scp-action@master
        with:
          # host: ${{ needs.provision_droplet.outputs.IPAddress}}
          host: 165.22.199.251
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './'
          target: 'dasea-tool'
