name: ls content
on:
  # Only allow manual triggers for now
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  list_content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ls -la
        run: ls -la

      
