name: Dispatch droplet destroy
on:
  repository_dispatch:
    types: [destroy-droplet]

jobs:
  destroy-droplet:
    name: destroy
    runs-on: ubuntu-latest
    steps:
      - name: echo-test
        run: echo "Hello World!"
